### ISSUE TITLE
Can't find Discussions on https://app.pluralsight.com/library/courses/react-redux-react-router-es6/table-of-contents

### ISSUE THREAD

**Issue by DHill952** [coryhouse/ama#24]
Hi - 
Sorry to post this here but I just can't find a 'Discussions' label on the product page.

I was attempting my first 'npm start' and I got this:

 PS C:\Users\david\Documents\vscode-projects\react-redux-react-router-es6\03\demos\before> npm start

> ps-redux@ start C:\Users\david\Documents\vscode-projects\react-redux-react-router-es6\03\demos\before
> webpack-dev-server --config webpack.config.dev.js --port 3000

i ｢wds｣: Project is running at http://localhost:3000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\david\Documents\vscode-projects\react-redux-react-router-es6\03\demos\before
i ｢wds｣: 404s will fallback to /index.html
× ｢wdm｣:    33 modules

ERROR in ./src/index.js
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (C:\Users\david\Documents\vscode-projects\react-redux-react-router-es6\03\demos\before\node_modules\eslint\lib\config.js:268:39)
    at Config.getConfigHierarchy (C:\Users\david\Documents\vscode-projects\react-redux-react-router-es6\03\demos\before\node_modules\eslint\lib\config.js:192:43)
    at Config.getConfigVector (C:\Users\david\Documents\vscode-projects\react-redux-react-router-es6\03\demos\before\node_modules\eslint\lib\config.js:299:21)
    at Config.getConfig (C:\Users\david\Documents\vscode-projects\react-redux-react-router-es6\03\demos\before\node_modules\eslint\lib\config.js:342:29)
    at processText (C:\Users\david\Documents\vscode-projects\react-redux-react-router-es6\03\demos\before\node_modules\eslint\lib\cli-engine.js:181:33)
    at CLIEngine.executeOnText (C:\Users\david\Documents\vscode-projects\react-redux-react-router-es6\03\demos\before\node_modules\eslint\lib\cli-engine.js:690:40)
    at lint (C:\Users\david\Documents\vscode-projects\react-redux-react-router-es6\03\demos\before\node_modules\eslint-loader\index.js:263:17)       
    at Object.module.exports (C:\Users\david\Documents\vscode-projects\react-redux-react-router-es6\03\demos\before\node_modules\eslint-loader\index.js:258:21)
i ｢wdm｣: Failed to compile.

**Comment by coryhouse** [comment]
There's a discussion tab at the top: https://app.pluralsight.com/library/courses/react-redux-react-router-es6/table-of-contents

![image](https://user-images.githubusercontent.com/1688997/83659814-a70d7100-a589-11ea-9c54-58e8df7307d0.png)

Please post your issue there. That said, I show how to configure ESLint here: https://app.pluralsight.com/player?course=react-redux-react-router-es6&author=cory-house&name=react-redux-react-router-es6-m2&clip=19&mode=live

**Comment by DHill952** [comment]
Thanks for the answer. I made the changes to package.json and it compiled. 
FYI, this is what I see on  @table-of-contents:
![image](https://user-images.githubusercontent.com/66376366/83664979-c1028000-a598-11ea-842c-edeca06374fc.png)

**Comment by coryhouse** [comment]
That's odd. I just forwarded this to support. I believe everyone should be able to see the discussion tab.

**Comment by coryhouse** [comment]
And thanks for reporting!

**Comment by coryhouse** [comment]
Per support: In order to view the "Discussion" tab, the user will need an active subscription associated with the account.

**Comment by DHill952** [comment]
I have a subscription through my job - it's not a trial subscription; I've used it for months. Maybe it's scaled down.
